services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"  # Expose port 8000 for direct access
    networks:
      - fastapi-network

  nginx:
    image: nginx:latest
    container_name: fastapi-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx config
    ports:
      - "80:80"  # Expose port 80 for Nginx
    depends_on:
      - app
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge